kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sis-mysql-storage-pvc 
  namespace: sis
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 80Gi