apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maximo
  labels:
    name: maximo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: maximo-apps
    spec:
      imagePullSecrets:
      - name: harborkey  
      containers:
      - name: maximo-apps
        image: harbor.gdphdc.com/maximo/maximo:v0.0.9     
        imagePullPolicy: IfNotPresent
        env:
          - name: USER_MEM_ARGS
            value: "-Xms1024m -Xmx4096m -XX:MaxPermSize=512m"
        #容器存活探针
        livenessProbe:
          httpGet:
            path: /maximo
            port: 7001
          initialDelaySeconds: 180
          periodSeconds: 20
        #服务存活探针
        readinessProbe:
          httpGet:
            path: /maximo
            port: 7001
          initialDelaySeconds: 180
          periodSeconds: 20
        ports:
        - containerPort: 7001
        - containerPort: 13400
        #资源限制值
        resources:
          limits:
            cpu: 4
            memory: 6Gi
          requests:
            cpu: 1
            memory: 2Gi
