kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: maximo-log-pvc
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
