apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.fullname" . }}-jobservice"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
  secretKey: {{ .Values.secretKey | b64enc | quote }}
  JOBSERVICE_SECRET: {{ .Values.jobservice.secret | b64enc | quote }}
  UI_SECRET: {{ .Values.ui.secret | b64enc | quote }}