apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eap-redis
  labels:
    name: eap-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: eap-redis-apps
    spec:
      containers:
      - name: eap-redis-app
        image: redis
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379        
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: eap-redis-pvc 
