apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eap-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      type: eap-data-pv
