apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eap-storage-pvc
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
