apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eap-storage-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  selector:
    matchLabels:
      type: eap-storage
