apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eap-redis-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  selector:
    matchLabels:
      type: eap-redis-pv
