apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-jobservice-config
data:
  UI_SECRET: "U7C0yNin3ujPJwvL"
  JOBSERVICE_SECRET: "JvE17zTR4mJqSdlu"
  SECRET_KEY: "kLHyGDHr8UIsBrKg"
  MAX_JOB_WORKERS: "3"
  LOG_LEVEL: debug
  GODEBUG: netdns=cgo
  CONFIG_PATH: /etc/jobservice/app.conf
  config: |
    appname = jobservice
    runmode = dev
    [dev]
    httpport = 80
