apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.fullname" . }}-registry"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
  httpSecret: {{ .Values.registry.httpSecret | b64enc | quote }}
  {{- $storage := .Values.registry.storage }}
  {{- $type := $storage.type }}
  {{- if eq $type "azure" }}
  accountkey: {{ $storage.azure.accountkey | b64enc | quote }}
  {{- else if eq $type "s3" }}
  {{- if $storage.s3.accesskey }}
  accesskey: {{ $storage.s3.accesskey | b64enc | quote }}
  {{- end }}
  {{- if $storage.s3.secretkey }}
  secretkey: {{ $storage.s3.secretkey | b64enc | quote }}
  {{- end }}
  {{- else if eq $type "swift" }}
  password: {{ $storage.swift.password }}
  {{- if $storage.swift.secretkey }}
  secretkey: {{ $storage.swift.secretkey }}
  {{- end }}
  {{- if $storage.swift.accesskey }}
  accesskey: {{ $storage.swift.accesskey }}
  {{- end }}
  {{- else if eq $type "oss" }}
  accesskeysecret: {{ $storage.oss.accesskeysecret }}
  {{- end }}