apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-storage-claim 
  labels:
    run: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: rbd