{{ if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "harbor.fullname" . }}-ingress"
  labels:
{{ include "harbor.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
{{ if eq .Values.externalProtocol "https" }}
  tls:
  - hosts:
    - "{{ .Values.externalDomain }}"
    - "{{ template "harbor.notaryFQDN" . }}"
    {{ if eq .Values.ingress.tls.secretName "" }}
    secretName: "{{ template "harbor.fullname" . }}-ingress"
    {{ else }}
    secretName: {{ .Values.ingress.tls.secretName }}
    {{ end }}
{{ end }}
  rules:
  - host: "{{ .Values.externalDomain }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "harbor.fullname" . }}-ui
          servicePort: 80
  - host: "{{ template "harbor.notaryFQDN" . }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "harbor.notaryServiceName" . }}
          servicePort: 4443
{{ end }}