kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-storage-pvc 
  namespace: wordpress
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi