apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.fullname" . }}-adminserver"
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: adminserver
type: Opaque
data:
  secretKey: {{ .Values.secretKey | b64enc | quote }}
  EMAIL_PWD: {{ .Values.email.password | b64enc | quote }}
  HARBOR_ADMIN_PASSWORD: {{ .Values.harborAdminPassword | b64enc | quote }}
  POSTGRESQL_PASSWORD: {{ template "harbor.database.password" . }}
  JOBSERVICE_SECRET: {{ .Values.jobservice.secret | b64enc | quote }}
  UI_SECRET: {{ .Values.ui.secret | b64enc | quote }}
{{- if eq .Values.authenticationMode "ldap_auth" }} 
  LDAP_SEARCH_PWD: {{ .Values.ldap.searchPassword | b64enc | quote }} 
{{- end }}
{{ if .Values.clair.enabled }}
  CLAIR_DB_PASSWORD: {{ template "harbor.database.password" . }}
{{ end }}
