apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "harbor.fullname" . }}-adminserver"
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: adminserver
data:
  POSTGRESQL_HOST: "{{ template "harbor.database.host" . }}"
  POSTGRESQL_PORT: "{{ template "harbor.database.port" . }}"
  POSTGRESQL_USERNAME: "{{ template "harbor.database.username" . }}"
  POSTGRESQL_DATABASE: "{{ template "harbor.database.coreDatabase" . }}"
  EMAIL_HOST: "{{ .Values.email.host }}"
  EMAIL_PORT: "{{ .Values.email.port }}"
  EMAIL_USR: "{{ .Values.email.username }}"
  EMAIL_SSL: "{{ .Values.email.ssl }}"
  EMAIL_FROM: "{{ .Values.email.from }}"
  EMAIL_IDENTITY: "{{ .Values.email.identity }}"
  EMAIL_INSECURE: "{{ .Values.email.insecure }}"
  EXT_ENDPOINT: "{{ template "harbor.externalURL" . }}"
  UI_URL: "http://{{ template "harbor.fullname" . }}-ui"
  JOBSERVICE_URL: "http://{{ template "harbor.fullname" . }}-jobservice"
  REGISTRY_URL: "http://{{ template "harbor.fullname" . }}-registry:5000"
  TOKEN_SERVICE_URL: "http://{{ template "harbor.fullname" . }}-ui/service/token"
  WITH_NOTARY: "{{ .Values.notary.enabled }}"
  NOTARY_URL: "http://{{ template "harbor.notaryServiceName" . }}:4443"
  LOG_LEVEL: "info"
  IMAGE_STORE_PATH: "/" # This is a temporary hack.
  AUTH_MODE: "{{ .Values.authenticationMode }}"
  SELF_REGISTRATION: "{{ .Values.selfRegistration }}"
  LDAP_URL: "{{ .Values.ldap.url }}"
  LDAP_SEARCH_DN: "{{ .Values.ldap.searchDN }}"
  LDAP_BASE_DN: "{{ .Values.ldap.baseDN }}"
  LDAP_FILTER: "{{ .Values.ldap.filter }}"
  LDAP_UID: "{{ .Values.ldap.uid }}"
  LDAP_SCOPE: "{{ .Values.ldap.scope }}"
  LDAP_TIMEOUT: "{{ .Values.ldap.timeout }}"
  LDAP_VERIFY_CERT: "{{ .Values.ldap.verifyCert }}"
  DATABASE_TYPE: "postgresql"
  PROJECT_CREATION_RESTRICTION: "everyone"
  VERIFY_REMOTE_CERT: "off"
  MAX_JOB_WORKERS: "3"
  TOKEN_EXPIRATION: "30"
  CFG_EXPIRATION: "5"
  GODEBUG: "netdns=cgo"
  ADMIRAL_URL: "NA"
  RESET: "false"
  WITH_CLAIR: "{{ .Values.clair.enabled }}"
  CLAIR_DB_HOST: "{{ template "harbor.database.host" . }}"
  CLAIR_DB_PORT: "{{ template "harbor.database.port" . }}"
  CLAIR_DB_USERNAME: "{{ template "harbor.database.username" . }}"
  CLAIR_DB: "{{ template "harbor.database.clairDatabase" . }}"
  CLAIR_URL: "http://{{ template "harbor.fullname" . }}-clair:6060"
  UAA_ENDPOINT: ""
  UAA_CLIENTID: ""
  UAA_CLIENTSECRET: ""
  UAA_VERIFY_CERT: "True"
  REGISTRY_STORAGE_PROVIDER_NAME: "{{ .Values.registry.storage.type }}"
  WITH_CHARTMUSEUM: "{{ .Values.chartmuseum.enabled }}"
  CHART_REPOSITORY_URL: "http://{{ template "harbor.fullname" . }}-chartmuseum"