kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: solo-data-pvc
  namespace: solo
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi