apiVersion: v1
kind: Service
metadata:
  labels:
    app: vmware-exporter
    release: vmware-exporter
  name: vmware-exporter
spec:
  ports:
  - port: 9272
    protocol: TCP
    targetPort: 9272
  selector:
    app: vmware-exporter

