apiVersion: v1
kind: Service
metadata:
  name: gogs
spec:
  ports:
    - port: 80
      name: http
      targetPort: 3000
    - port: 22
      name: git
      targetPort: 22
  selector:
    name: gogs-apps
