kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  nexus-data-pvc
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
