apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogs-data-pvc
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      type: gogs-data-pv
