apiVersion: v1
kind: PersistentVolume
metadata:
  name: gogs-data-pv
  labels:
    type: gogs-data-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /opt/k8s/harbor
    server: 10.45.10.148