apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogs-storage-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
