apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogs-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  selector:
    matchLabels:
      type: gogs-storage
