kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: kube-system
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
