apiVersion: v1
kind: Service
metadata:
  labels:
    run: snmp-explorter
  name: snmp-explorter
spec:
  ports:
  - port: 9116
    protocol: TCP
    targetPort: 9116
  selector:
    run: snmp-explorter
