{{- if .Values.chartmuseum.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.fullname" . }}-chartmuseum"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
  CACHE_REDIS_PASSWORD: "{{ template "harbor.redis.password" }}"
  BASIC_AUTH_PASS: {{ .Values.ui.secret | b64enc | quote }}
{{- end }}