apiVersion: extensions/v1beta1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: eap
  labels:
    name: eap
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: eap-apps
    spec:
      imagePullSecrets:
      - name: harborkey
      containers:
      - name: eap-app
        image: harbor.gdphdc.com/admineap/admineap:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 800m
            memory: 4096Mi
          requests:
            cpu: 200m
            memory: 512Mi
        volumeMounts:
        - mountPath: /data
          name: eap-data
      volumes:
        - name: eap-data
          persistentVolumeClaim:
            claimName: eap-data-pvc
---
