apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taiga-config-pv-claim
  labels:
    app: taiga
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi