
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taigamedia-pv-claim
  labels:
    app: taiga
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
