apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gogs
  annotations:
    ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
  - hosts: 
    - gogs.gdphdc.com
    secretName: gogs-ingress-secret 
  rules:
  - host: gogs.gdphdc.com
    http:
      paths:
      - path: /
        backend:
          serviceName: gogs
          servicePort: 80
