apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gogs
spec:
  rules:
  - host: gogs.gdphdc.com
    http:
      paths:
      - path: /
        backend:
          serviceName: gogs
          servicePort: 80
